version: '3.5'
services:
    nginx:
        image: nginx:latest
        container_name: animal_translator_nginx
        working_dir: /code
        tty: true
        links:
            - fpm
        ports:
            - "80:80"
        volumes:
            - .:/code
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    fpm:
        build:
            context: ./docker/
            args:
                - "INSTALL_XDEBUG=false"
        container_name: animal_translator_fpm
        working_dir: /code
        user: ${CURRENT_UID}
        tty: true
        volumes:
            - .:/code
            - ./docker/php-docker.ini:/usr/local/etc/php/conf.d/php-docker.ini
    node:
        image: node:14
        container_name: animal_translator_node
        command: npm run watch
        working_dir: /app
        tty: true
        volumes:
         - .:/app
